---
title: "Tutorial for Linear model & Linear Mixed Effects in R"
author: "Hyuksu Ryu"
date: "October 7, 2017"
output:
  beamer_presentation:
    incremental: yes
    theme: Singapore
    colortheme: dolphin
    outertheme: smoothbars 
    innertheme: circles
    fonttheme: structurebold
    toc: yes
  slidy_presentation:
    incremental: yes
    toc: yes
---

# Intro of Intro
## Setting packages

```{r, message=FALSE, warning=FALSE}
if(!is.element('caret', installed.packages()[, 1])){
  install.packages('caret')
}
if(!is.element('dplyr', installed.packages()[, 1])){
  install.packages('dplyr')
}
if(!is.element('lme4', installed.packages()[, 1])){
  install.packages('lme4')
}
require('caret')
require('dplyr')
require('lme4')
```


# Linear model {.allowframebreaks}
## Setting data frame

```{r}
pitch = c(233, 204, 242, 130, 112, 142)
sex = c(rep("female", 3), rep("male", 3))
my.df = data.frame(sex, pitch) # data frame of 6 informants
my.df
```

## Linear model
* Linear model
```{r}
xmdl = lm(pitch ~ sex, my.df)
summary(xmdl)
```

```{r}
mean(my.df[my.df$sex=="female",]$pitch)
```

